import { MigrationInterface, QueryRunner } from "typeorm";

export class Category1758084360329 implements MigrationInterface {
    name = 'Category1758084360329'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`categories\` ADD \`is_deleted\` tinyint NOT NULL DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE \`shipping\` DROP COLUMN \`created_by\``);
        await queryRunner.query(`ALTER TABLE \`shipping\` ADD \`created_by\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`shipping\` DROP COLUMN \`updated_by\``);
        await queryRunner.query(`ALTER TABLE \`shipping\` ADD \`updated_by\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`payments\` DROP COLUMN \`created_by\``);
        await queryRunner.query(`ALTER TABLE \`payments\` ADD \`created_by\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`payments\` DROP COLUMN \`updated_by\``);
        await queryRunner.query(`ALTER TABLE \`payments\` ADD \`updated_by\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`brands\` DROP COLUMN \`created_by\``);
        await queryRunner.query(`ALTER TABLE \`brands\` ADD \`created_by\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`brands\` DROP COLUMN \`updated_by\``);
        await queryRunner.query(`ALTER TABLE \`brands\` ADD \`updated_by\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`categories\` DROP COLUMN \`created_by\``);
        await queryRunner.query(`ALTER TABLE \`categories\` ADD \`created_by\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`categories\` DROP COLUMN \`updated_by\``);
        await queryRunner.query(`ALTER TABLE \`categories\` ADD \`updated_by\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`sub-category\` DROP COLUMN \`created_by\``);
        await queryRunner.query(`ALTER TABLE \`sub-category\` ADD \`created_by\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`sub-category\` DROP COLUMN \`updated_by\``);
        await queryRunner.query(`ALTER TABLE \`sub-category\` ADD \`updated_by\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`reviews\` DROP COLUMN \`created_by\``);
        await queryRunner.query(`ALTER TABLE \`reviews\` ADD \`created_by\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`reviews\` DROP COLUMN \`updated_by\``);
        await queryRunner.query(`ALTER TABLE \`reviews\` ADD \`updated_by\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`products\` DROP COLUMN \`created_by\``);
        await queryRunner.query(`ALTER TABLE \`products\` ADD \`created_by\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`products\` DROP COLUMN \`updated_by\``);
        await queryRunner.query(`ALTER TABLE \`products\` ADD \`updated_by\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`sizes\` DROP COLUMN \`created_by\``);
        await queryRunner.query(`ALTER TABLE \`sizes\` ADD \`created_by\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`sizes\` DROP COLUMN \`updated_by\``);
        await queryRunner.query(`ALTER TABLE \`sizes\` ADD \`updated_by\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`colors\` DROP COLUMN \`created_by\``);
        await queryRunner.query(`ALTER TABLE \`colors\` ADD \`created_by\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`colors\` DROP COLUMN \`updated_by\``);
        await queryRunner.query(`ALTER TABLE \`colors\` ADD \`updated_by\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`discounts\` DROP COLUMN \`created_by\``);
        await queryRunner.query(`ALTER TABLE \`discounts\` ADD \`created_by\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`discounts\` DROP COLUMN \`updated_by\``);
        await queryRunner.query(`ALTER TABLE \`discounts\` ADD \`updated_by\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`product_discount\` DROP COLUMN \`created_by\``);
        await queryRunner.query(`ALTER TABLE \`product_discount\` ADD \`created_by\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`product_discount\` DROP COLUMN \`updated_by\``);
        await queryRunner.query(`ALTER TABLE \`product_discount\` ADD \`updated_by\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`product_item\` DROP COLUMN \`created_by\``);
        await queryRunner.query(`ALTER TABLE \`product_item\` ADD \`created_by\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`product_item\` DROP COLUMN \`updated_by\``);
        await queryRunner.query(`ALTER TABLE \`product_item\` ADD \`updated_by\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`order_detial\` DROP COLUMN \`created_by\``);
        await queryRunner.query(`ALTER TABLE \`order_detial\` ADD \`created_by\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`order_detial\` DROP COLUMN \`updated_by\``);
        await queryRunner.query(`ALTER TABLE \`order_detial\` ADD \`updated_by\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP COLUMN \`created_by\``);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD \`created_by\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP COLUMN \`updated_by\``);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD \`updated_by\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`created_by\``);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`created_by\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`updated_by\``);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`updated_by\` varchar(255) NULL`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`updated_by\``);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`updated_by\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`created_by\``);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`created_by\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP COLUMN \`updated_by\``);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD \`updated_by\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP COLUMN \`created_by\``);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD \`created_by\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`order_detial\` DROP COLUMN \`updated_by\``);
        await queryRunner.query(`ALTER TABLE \`order_detial\` ADD \`updated_by\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`order_detial\` DROP COLUMN \`created_by\``);
        await queryRunner.query(`ALTER TABLE \`order_detial\` ADD \`created_by\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`product_item\` DROP COLUMN \`updated_by\``);
        await queryRunner.query(`ALTER TABLE \`product_item\` ADD \`updated_by\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`product_item\` DROP COLUMN \`created_by\``);
        await queryRunner.query(`ALTER TABLE \`product_item\` ADD \`created_by\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`product_discount\` DROP COLUMN \`updated_by\``);
        await queryRunner.query(`ALTER TABLE \`product_discount\` ADD \`updated_by\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`product_discount\` DROP COLUMN \`created_by\``);
        await queryRunner.query(`ALTER TABLE \`product_discount\` ADD \`created_by\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`discounts\` DROP COLUMN \`updated_by\``);
        await queryRunner.query(`ALTER TABLE \`discounts\` ADD \`updated_by\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`discounts\` DROP COLUMN \`created_by\``);
        await queryRunner.query(`ALTER TABLE \`discounts\` ADD \`created_by\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`colors\` DROP COLUMN \`updated_by\``);
        await queryRunner.query(`ALTER TABLE \`colors\` ADD \`updated_by\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`colors\` DROP COLUMN \`created_by\``);
        await queryRunner.query(`ALTER TABLE \`colors\` ADD \`created_by\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`sizes\` DROP COLUMN \`updated_by\``);
        await queryRunner.query(`ALTER TABLE \`sizes\` ADD \`updated_by\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`sizes\` DROP COLUMN \`created_by\``);
        await queryRunner.query(`ALTER TABLE \`sizes\` ADD \`created_by\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`products\` DROP COLUMN \`updated_by\``);
        await queryRunner.query(`ALTER TABLE \`products\` ADD \`updated_by\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`products\` DROP COLUMN \`created_by\``);
        await queryRunner.query(`ALTER TABLE \`products\` ADD \`created_by\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`reviews\` DROP COLUMN \`updated_by\``);
        await queryRunner.query(`ALTER TABLE \`reviews\` ADD \`updated_by\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`reviews\` DROP COLUMN \`created_by\``);
        await queryRunner.query(`ALTER TABLE \`reviews\` ADD \`created_by\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`sub-category\` DROP COLUMN \`updated_by\``);
        await queryRunner.query(`ALTER TABLE \`sub-category\` ADD \`updated_by\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`sub-category\` DROP COLUMN \`created_by\``);
        await queryRunner.query(`ALTER TABLE \`sub-category\` ADD \`created_by\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`categories\` DROP COLUMN \`updated_by\``);
        await queryRunner.query(`ALTER TABLE \`categories\` ADD \`updated_by\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`categories\` DROP COLUMN \`created_by\``);
        await queryRunner.query(`ALTER TABLE \`categories\` ADD \`created_by\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`brands\` DROP COLUMN \`updated_by\``);
        await queryRunner.query(`ALTER TABLE \`brands\` ADD \`updated_by\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`brands\` DROP COLUMN \`created_by\``);
        await queryRunner.query(`ALTER TABLE \`brands\` ADD \`created_by\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`payments\` DROP COLUMN \`updated_by\``);
        await queryRunner.query(`ALTER TABLE \`payments\` ADD \`updated_by\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`payments\` DROP COLUMN \`created_by\``);
        await queryRunner.query(`ALTER TABLE \`payments\` ADD \`created_by\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`shipping\` DROP COLUMN \`updated_by\``);
        await queryRunner.query(`ALTER TABLE \`shipping\` ADD \`updated_by\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`shipping\` DROP COLUMN \`created_by\``);
        await queryRunner.query(`ALTER TABLE \`shipping\` ADD \`created_by\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`categories\` DROP COLUMN \`is_deleted\``);
    }

}
